# Web Server configuration
server:
  port: 8989

# Database configuration
data-source:
  host: upbos.cn
  port: 5432
  user: ${ACC_DB_USER}
  password: ${ACC_DB_PASSWORD}
  database: acc

# Send email configuration
email:
  host: smtp.126.com
  port: 25
  user: ${ACC_EMAIL_USER}
  password: ${ACC_EMAIL_PASSWORD}

# Log configuration
logger:
  level: debug
  console: true
  file:
    file-name: ./logs/acc.log
    max-size: 100
    max-backups: 3
    max-age: 15
    compress: true