package consts

const (

	// ACCOUNT_TYPE_ASSETS 账户类型 - 资产
	ACCOUNT_TYPE_ASSETS = 1

	// ACCOUNT_TYPE_DEBT 账户类型 - 负债
	ACCOUNT_TYPE_DEBT = 2

	// ACCOUNT_TYPE_EQUITY 账户类型 - 权益
	ACCOUNT_TYPE_EQUITY = 3

	// ACCOUNT_TYPE_INCOME 账户类型 - 收入
	ACCOUNT_TYPE_INCOME = 4

	// ACCOUNT_TYPE_EXPENSES 账户类型 - 支出
	ACCOUNT_TYPE_EXPENSES = 5

	// TRANSACTION_TYPE_INIT 初始账户
	TRANSACTION_TYPE_INIT = 1

	// TRANSACTION_TYPE_BALANCE 余额调整
	TRANSACTION_TYPE_BALANCE = 2

	// TRANSACTION_TYPE_INCOME 收入
	TRANSACTION_TYPE_INCOME = 3

	// TRANSACTION_TYPE_EXPENSES 支出
	TRANSACTION_TYPE_EXPENSES = 4

	// TRANSACTION_TYPE_LEND 借出
	TRANSACTION_TYPE_LEND = 5

	// TRANSACTION_TYPE_BORROW 借入
	TRANSACTION_TYPE_BORROW = 6

	// TRANSACTION_TYPE_DEBT_IN 收债
	TRANSACTION_TYPE_DEBT_IN = 7

	// TRANSACTION_TYPE_DEBT_OUT 还债
	TRANSACTION_TYPE_DEBT_OUT = 8

	// TRANSACTION_TYPE_TRANSFER 转账
	TRANSACTION_TYPE_TRANSFER = 9
)
