package common

const (

	// ACCOUNT_TYPE_ASSETS 账户类型 - 资产
	ACCOUNT_TYPE_ASSETS = 1

	// ACCOUNT_TYPE_DEBT 账户类型 - 负债
	ACCOUNT_TYPE_DEBT = 2

	// ACCOUNT_TYPE_EQUITY 账户类型 - 权益
	ACCOUNT_TYPE_EQUITY = 3

	// ACCOUNT_TYPE_INCOME 账户类型 - 收入
	ACCOUNT_TYPE_INCOME = 4

	// ACCOUNT_TYPE_EXPENSES 账户类型 - 支出
	ACCOUNT_TYPE_EXPENSES = 5
)
